# 端口号
server:
  port: 8888


# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music_sys?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://mysql:3306/music_sys?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源
    type: com.alibaba.druid.pool.DruidDataSource
  # 返回json的全局时间格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB          # 单个文件大小
      max-request-size: 100MB      # 总文件大小

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.huan.music_sys.domain

  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info

web.upload-path: /usr/local/ueditorUpload

web.front-path: /usr/local/ueditorUpload

spring.resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path},file:${web.front-path}
