version: '3'

services:
  nginx_client: # 服务名称
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - /root/music/nginx_client/html:/usr/share/nginx/html
      - /root/music/nginx_client/nginx.conf:/etc/nginx/nginx.conf
    privileged: true  # 这个必须要，解决nginx文件调用的权限问题
  nginx_manage: # 服务名称
    image: nginx:latest
    ports:
      - 81:81
    volumes:
      - /root/music/nginx_manage/html:/usr/share/nginx/html
      - /root/music/nginx_manage/nginx.conf:/etc/nginx/nginx.conf
    privileged: true  # 这个必须要，解决nginx文件调用的权限问题
  mysql:
    image: mysql:8.0.17
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
  music_sys:
    image: music_sys:latest
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 8888:8888
    volumes:
      - /usr/local/ueditorUpload:/usr/local/ueditorUpload
    depends_on:
      - mysql
